name: Pull Request - Check Protobuf - Go

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch all branches
        run: git fetch --all
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: false
          cache: true
      - name: Generate Go Source
        shell: bash
        run: |
          make pipeline-build
      - name: Generate Go Gateway source
        shell: bash
        run: |
          make pipeline-build-gateway
      - name: Go mod tidy
        run: |
          go mod tidy
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
